name: awesome_flutter_extensions
description: >
  A Flutter Extension to remove boilerplate when accessing
  ancestor context properties
version: 1.1.1
homepage: https://bestofcode.dev
repository: https://github.com/nank1ro/awesome_flutter_extensions

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter: null
